spring.application.name=myapp

# Wir nutzen Platzhalter für die echten Werte
spring.datasource.url=jdbc:postgresql://dpg-d56kjumuk2gs73ciio50-a.frankfurt-postgres.render.com/webtech_db_exbe
spring.datasource.username=webtech_db_exbe_user
spring.datasource.password=n1WHJzbvmr36zbpdYOuFpHablYr8mWn9

# Das sorgt dafür, dass Tabellen automatisch erstellt werden
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false