spring.application.name=myapp

# Wir nutzen Platzhalter für die echten Werte
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Das sorgt dafür, dass Tabellen automatisch erstellt werden
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false